/*ZCS:1.0,5.0:
Information : Generated by ZK Studio Style Designer, compatible with ZK 3.5.2;
Don't edit any content between SEC and SEC_E comments.
*/<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>

</body>
</html>/*SEC:WINDOW-EMBEDDED:myname1*/

/*SEC_E*//*SEC:CALENDAR:myname2*/

/*SEC_E*/